export const dataGitProy = [
  {
    id: 1,
    name: "Urban pro",
    link:"https://github.com/Agus-Albarracin/Urban-pro",
    stack: "Full Stack",
    description: "Sistema de gestión de cursos y vista usuario con Nest, React, TypeScript y Docker",
    image: "/assets/github-icon.svg",
  },
  {
    id: 2,
    name: "Landing Page",
    link:"https://github.com/Agus-Albarracin/starseare-webpage",
    stack: "Front end",
    description: "Landing page para visualización e información de empresa, Next.js.",
    image: "/assets/github-icon.svg",
  },
  {
    id: 4,
    name: "Libreria Full Stack",
    link:"https://github.com/Agus-Albarracin/google-cactus",
    stack: "Back end/ ops",
    description: "Librería para sanitización de recuperación de datos Google Auth para Node.js",
    image: "/assets/github-icon.svg",
  },
  {
    id: 5,
    name: "E-commerce",
    link:"https://github.com/Agus-Albarracin/disturbiaarg",
    stack: "Full Stack",
    description: "Ventas online y gestión de stock, integracion de billeteras, Google Auth. ",
    image: "/assets/github-icon.svg",
  },
  {
    id: 6,
    name: "Invitación",
    link:"https://github.com/Agus-Albarracin/invit-fest",
    stack: "Front end",
    description: "Invitaciones para fiestas especialmente responsivas y adaptables.",
    image: "/assets/github-icon.svg",
  },
  {
    id: 7,
    name: "Webhook",
    link:"https://github.com/Agus-Albarracin/callbellhook",
    stack: "Backend",
    description: "Webhook para integración de ChatBot con IA, inyección de codigo y rest API.",
    image: "/assets/github-icon.svg",
  },
  {
    id: 8,
    name: "Landing Page",
    link:"https://github.com/Agus-Albarracin/starseare-webpage",
    stack: "Front end",
    description: "Landing page para visualización e información de empresa.",
    image: "/assets/github-icon.svg",
  },
  {
    id: 9,
    name: "Página Web ",
    link:"https://github.com/Agus-Albarracin/cactus-webpage",
    stack: "Front end",
    description: "Pagina web para visualización, presentación e información de empresa.",
    image: "/assets/github-icon.svg",
  },
  {
    id: 10,
    name: "E-commerce",
    link: "https://github.com/Agus-Albarracin/uuid-store",
    stack: "Full Stack",
    description: "Ecommerce para empresa de indumentaria con sistema ERP y CRM",
    image: "/assets/github-icon.svg",
  }
];